language: cpp

# fake providing compiler setting
compiler: gcc

before_script:
    - "bash --version | head -n 1"
    - "export PATH=$PWD:$PATH"

script:
    - "pkgbox -vvv -D test foo bar"
    - "pkgbox -v media-gfx/graphicsmagick install"

after_script:
    - "/usr/local/bin/gm -version"

