language: cpp

# fake providing compiler setting
compiler: gcc

before_script:
    - "bash --version | head -n 1"
    - "export PATH=$PWD:$PATH"
    - "mkdir ~/.pkgbox && cp -v conf.sample ~/.pkgbox/conf"

script:
    - "pkgbox -h"
    - "pkgbox -vvv -D test foo bar"
    - "pkgbox -v media-gfx/graphicsmagick install"

after_script:
    - "~/local/bin/gm -version"

