language: cpp

# Set gcc as compiler for the demo program GNU "Hello world!".
compiler: gcc

# Set $TERM to "linux" to prevent pkgbox from setting the terminal
# window title, as the "xterm" emulation seems not to work with it.
env: TERM=linux

# Display bash version info, include pkgbox script in executable path,
# clone the pkgbox configuration and change the option "prefix".
before_script:
    - "bash --version | head -n 1"
    - "export PATH=$PWD:$PATH"
    - "mkdir ~/.pkgbox"
    - "sed 's/#O\\[prefix\\]=.*/O\\[prefix\\]=\"$HOME\\/local\"/' conf.sample >~/.pkgbox/conf"

# Tests:
# 1) Usage/Synopsis/Help
# 2) Test suite
# 3) Display package details
# 4) Build and install package app-misc/hello with NLS-support
script:
    - "pkgbox -h"
    - "pkgbox -vvv -T"
    - "pkgbox app-misc/hello"
    - "pkgbox -v -F -nls app-misc/hello install"

# Test the GNU hello program
after_script:
    - "~/local/bin/hello --next-generation"

