language: cpp

# fake providing compiler setting
compiler: gcc

before_script:
    - "bash --version | head -n 1"
    - "export PATH=$PWD:$PATH"
    - "mkdir ~/.pkgbox && cp -v conf.sample ~/.pkgbox/conf"

script:
    - "pkgbox -h"
    - "pkgbox -vvv -T"
    - "pkgbox app-misc/hello info"
    - "pkgbox -v app-misc/hello install"

after_script:
    - "~/local/bin/hello --next-generation"

